# syntax=docker/dockerfile:1
FROM golang:1.24 AS build
WORKDIR /app
COPY . .
ENV GOTOOLCHAIN=auto
RUN go mod download
ARG WEBUI_TAG
RUN if [ "$WEBUI_TAG" = "1" ]; then go build -tags webui -o /out/webapi ./cmd/webapi; else go build -o /out/webapi ./cmd/webapi; fi

FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=build /out/webapi /app/webapi
EXPOSE 8080
USER 65532:65532
ENTRYPOINT ["/app/webapi"]
